### PR TITLE
Add Python 3.7 to Travis-CI tests

### PR DESCRIPTION
**Pull request by mimischi**

### CODE REVIEW

**Comment by mimischi** [comment]
We'll keep this open for now.

Currently we are using a workaround, because Travis-CI does not support Python 3.7 (https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442). Also some dependency is pulling in `pytables`, which needs `hdf5`. The lack of a wheel file blocks the installation on Python 3.7 (https://github.com/PyTables/PyTables/issues/704).

**Comment by kain88-de** [comment]
mdsynthesis is pulling in that dependency. An update to the new datreant version will fix this.

**Comment by kain88-de** [comment]
give python 3.7 another month until all packages are updated.

**Comment by mimischi** [comment]
Currently blocked by #99.

**Comment by mimischi** [comment]
Now that PR #110 is merged, we can actually also merge this. As a note, with Python 3.7 we get some deprecation warnings during the `pytest` call. Some are ours, some from dependencies:

```python
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pathlib2/__init__.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sequence
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
/home/travis/build/bio-phys/MDBenchmark/mdbenchmark/mdengines/utils.py:32: DeprecationWarning: invalid escape sequence \.
  "gromacs": [".*/bench\.job", ".*\.tpr", ".*\.mdp"],
/home/travis/build/bio-phys/MDBenchmark/mdbenchmark/mdengines/utils.py:32: DeprecationWarning: invalid escape sequence \.
  "gromacs": [".*/bench\.job", ".*\.tpr", ".*\.mdp"],
/home/travis/build/bio-phys/MDBenchmark/mdbenchmark/mdengines/utils.py:32: DeprecationWarning: invalid escape sequence \.
  "gromacs": [".*/bench\.job", ".*\.tpr", ".*\.mdp"],
/home/travis/build/bio-phys/MDBenchmark/mdbenchmark/mdengines/utils.py:33: DeprecationWarning: invalid escape sequence \.
  "namd": [".*/bench\.job", ".*\.namd", ".*\.psf", ".*\.pdb"],
/home/travis/build/bio-phys/MDBenchmark/mdbenchmark/mdengines/utils.py:33: DeprecationWarning: invalid escape sequence \.
  "namd": [".*/bench\.job", ".*\.namd", ".*\.psf", ".*\.pdb"],
/home/travis/build/bio-phys/MDBenchmark/mdbenchmark/mdengines/utils.py:33: DeprecationWarning: invalid escape sequence \.
  "namd": [".*/bench\.job", ".*\.namd", ".*\.psf", ".*\.pdb"],
/home/travis/build/bio-phys/MDBenchmark/mdbenchmark/mdengines/utils.py:33: DeprecationWarning: invalid escape sequence \.
  "namd": [".*/bench\.job", ".*\.namd", ".*\.psf", ".*\.pdb"],
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/matplotlib/cbook/__init__.py:2349: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(obj, collections.Iterator):
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/matplotlib/cbook/__init__.py:2366: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return list(data) if isinstance(data, collections.MappingView) else data
```

**Pull request merged**
